name: Publish to NPM

on:
  push:
    tags:
      - "v*"  # ✅ Runs when a tag like v1.0.0 is pushed
  workflow_dispatch:  # ✅ Allows manual execution from GitHub UI

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
